[package]
name = "kak-session-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "fs", "net", "sync", "macros", "rt", "io-util"] }
tokio-macros = "2.4.0"
